#ifndef QUANTIZATION_CONFIG_H
#define QUANTIZATION_CONFIG_H

#define NPU_VOCAB_SIZE 64
#define NPU_D_MODEL 16
#define NPU_CONTEXT_LENGTH 16
#define NPU_D_FF 32
#define NPU_ATTENTION_HEADS 1
#define NPU_ATTENTION_DK_SHIFT 2
#define NPU_FFN_SCALING_SHIFT -3
#define NPU_FFN_ACTIVATION_SHIFT -3
#define NPU_SOFTMAX_INPUT_SHIFT -3

/* Dequantized value = int8_value * 2^(NPU_<NAME>_SCALE_SHIFT). */
#define NPU_TOKEN_EMBEDDING_SCALE_SHIFT -4
#define NPU_POSITION_EMBEDDING_SCALE_SHIFT -5
#define NPU_W_Q_SCALE_SHIFT -7
#define NPU_B_Q_SCALE_SHIFT -6
#define NPU_W_K_SCALE_SHIFT -7
#define NPU_B_K_SCALE_SHIFT -9
#define NPU_W_V_SCALE_SHIFT -6
#define NPU_B_V_SCALE_SHIFT -7
#define NPU_W_O_SCALE_SHIFT -7
#define NPU_B_O_SCALE_SHIFT -8
#define NPU_W_FF1_SCALE_SHIFT -6
#define NPU_B_FF1_SCALE_SHIFT -7
#define NPU_W_FF2_SCALE_SHIFT -6
#define NPU_B_FF2_SCALE_SHIFT -8
#define NPU_W_VOCAB_SCALE_SHIFT -6
#define NPU_B_VOCAB_SCALE_SHIFT -8

#endif
